### ISSUE TITLE
Mizzing zip

### ISSUE THREAD

**Issue by MatsK** [mjakiani/OpenStack_Train_DevStack-OVA-VM-VirtualBox-Ubuntu_18_LTS#1]
It looks like the file DevStack_OpenStack_Train-Ubuntu_18_LTS.z30 is missing

**Comment by mjakiani** [comment]
These are all the zip files, will check again and then close this

**Comment by MatsK** [comment]
OK, I used 7-zip to unpack the zip with if that's to any help.

**Comment by MatsK** [comment]
![Screenshot 2020-03-28 13 37 40](https://user-images.githubusercontent.com/200207/77823209-8f34ef00-70f9-11ea-8d86-b1c7db0d7eef.png)

**Comment by mjakiani** [comment]
Unable to access the original copy due to Corona lockdown , will check it and meanwhile will create a new VM. Upload is slow at my current place so it might take some time.

**Comment by mjakiani** [comment]
Please check now. Upload is complete. Took some time on 1 Mb/s upstream.

**Comment by MatsK** [comment]
God work! I only had one issue, my VMware workstation complains that the ovf is mallformed, but then present an option to import it with more relaxed checking. And it worked.

Thx
/Mats

**Comment by mjakiani** [comment]
Try it with VirtualBox for a more streamlined experience
